// _11ty/search-index.js
//
// Builds one search index per locale from the rendered pages, and writes
// it as a plain script, assets/search/<locale>.js, that assigns the index
// to a global. A <script src> tag loads it, which works from file:// where
// fetch() and WebAssembly loading are blocked, and works on old browsers.
// See ADR-003.
//
// Only the region marked data-search="body" in each page is indexed, so
// headers, footers and navigation do not pollute results.

const fs = require("node:fs");
const path = require("node:path");

const entries = new Map(); // locale -> Map(url -> entry)

function decodeEntities(s) {
  return s
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&#x27;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)));
}

function textOf(html) {
  return decodeEntities(
    html
      .replace(/<script[\s\S]*?<\/script>/gi, " ")
      .replace(/<style[\s\S]*?<\/style>/gi, " ")
      .replace(/<(br|\/p|\/li|\/h\d|\/tr|\/td|\/th|\/dd|\/dt)\b[^>]*>/gi, " . ")
      .replace(/<[^>]+>/g, " ")
  )
    .replace(/(\s*\.\s*){2,}/g, " . ")
    .replace(/\s+/g, " ")
    .trim();
}

function attr(html, re) {
  const m = html.match(re);
  return m ? decodeEntities(m[1]) : "";
}

// Called from a transform with the page's final HTML (before link
// rewriting). The layout marks what to index: the locale on <html>, the
// title and summary on the data-search="body" wrapper, which ends at the
// <!-- /search-body --> comment. Pages without that wrapper are skipped.
function collect({ url, html }) {
  const locale = attr(html, /<html[^>]*\bdata-locale="([^"]+)"/);
  if (!locale) return;
  const m = html.match(/<div[^>]*data-search="body"[^>]*>([\s\S]*?)<!-- \/search-body -->/);
  if (!m) return;
  const title = attr(html, /data-search-title="([^"]*)"/);
  const summary = attr(html, /data-search-summary="([^"]*)"/);
  const keywords = attr(html, /data-search-keywords="([^"]*)"/);
  const headings = [...m[1].matchAll(/<h[23][^>]*>([\s\S]*?)<\/h[23]>/gi)].map((h) => textOf(h[1]));
  const file = (url.endsWith("/") ? url + "index.html" : url).replace(/^\//, "");
  if (!entries.has(locale)) entries.set(locale, new Map());
  entries.get(locale).set(file, {
    u: file,
    t: title || "",
    s: summary || "",
    k: keywords || "",
    h: headings,
    b: textOf(m[1]),
  });
}

function write(outDir) {
  const dir = path.join(outDir, "assets", "search");
  fs.mkdirSync(dir, { recursive: true });
  const written = [];
  for (const [locale, map] of entries) {
    const docs = [...map.values()].sort((a, b) => a.u.localeCompare(b.u));
    const body =
      "/* Generated by _11ty/search-index.js. Do not edit. */\n" +
      "window.BALISE_SEARCH = window.BALISE_SEARCH || {};\n" +
      `window.BALISE_SEARCH[${JSON.stringify(locale)}] = ${JSON.stringify(docs)};\n`;
    const file = path.join(dir, `${locale}.js`);
    fs.writeFileSync(file, body);
    written.push({ locale, docs: docs.length, bytes: Buffer.byteLength(body) });
  }
  return written;
}

function reset() {
  entries.clear();
}

module.exports = { collect, write, reset };
